export const nikeProducts = [
    {
      id: 1,
      tags: "Just In",
      title: "Nike Air Force 1 Mid '07",
      description: "Men's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 10 795.00",
      imagesUrls: "/AllProducts/pro1.png",
    },
    {
      id: 2,
      tags: "Just In",
      title: "Nike Court Vision Low Next Nature",
      description: "Men's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 4 995.00",
      imagesUrls: "/AllProducts/pro2.png",
    },
    {
      id: 3,
      tags: "Just In",
      title: "Nike Air Force 1 PLT.AF.ORM",
      description: "Women's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 8 695.00",
      imagesUrls: "/AllProducts/pro3.png",
    },
    {
      id: 4,
      tags: "Just In",
      title: "Nike Air Force 1 React",
      description: "Men's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 13 295.00",
      imagesUrls: "/AllProducts/pro4.png",
    },
    {
      id: 5,
      tags: "Promo Exclusion",
      title: "Air Jordan 1 Elevate Low",
      description: "Women's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 11 895.00",
      imagesUrls: "/AllProducts/pro5.png",
    },
    {
      id: 6,
      tags: "Just In",
      title: "Nike Standard Issue",
      description: "Women's Basketball Jersey",
      color: "1 Colour",
      price: "MRP : ₹ 2 895.00",
      imagesUrls: "/AllProducts/pro6.png",
    },
    {
      id: 7,
      tags: "Promo Exclusion",
      title: "Nike Dunk Low Retro SE",
      description: "Men's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 9 695.00",
      imagesUrls: "/AllProducts/pro7.png",
    },
    {
      id: 8,
      tags: "Sustainable Materials",
      title: "Nike Dri-FIT UV Hyverse",
      description: "Men's Short Sleeve Graphic Fitness Top",
      color: "1 Colour",
      price: "MRP : ₹ 2 495.00",
      imagesUrls: "/AllProducts/pro8.png",
    },
    {
      id: 9,
      tags: "Just In",
      title: "Nike Court Vision Low",
      description: "Men's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 5 695.00",
      imagesUrls: "/AllProducts/pro9.png",
    },
    {
      id: 10,
      tags: "Just In",
      title: "Nike Dri-FIT Ready",
      description: "Men's Short Sleeve Fitness Top",
      color: "3 Colours",
      price: "MRP : ₹ 2 495.00",
      imagesUrls: "/AllProducts/pro10.png",
    },
    {
      id: 11,
      tags: "Just In",
      title: "Nike One Leak Protection: Period",
      description: "Women's Mid-Rise 18cm (approx.) Biker Shorts",
      color: "2 Colours",
      price: "MRP : ₹ 3 395.00",
      imagesUrls: "/AllProducts/pro11.png",
    },
    {
      id: 12,
      tags: "Just In",
      title: "Nike Air Force 1 LV8 3",
      description: "Older Kids' Shoe",
      color: "1 Colour",
      price: "MRP : ₹ 7 495.00",
      imagesUrls: "/AllProducts/pro12.png",
    },
    {
      id: 13,
      tags: "Just In",
      title: "Nike Blazer Low Platform",
      description: "Women's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 8 195.00",
      imagesUrls: "/AllProducts/pro13.png",
    },
    {
      id: 14,
      tags: "Just In",
      title: "Nike Air Force 1 '07",
      description: "Women's Shoe",
      color: "2 Colours",
      price: "MRP : ₹ 8 195.00",
      imagesUrls: "/AllProducts/pro14.png",
    },
    {
      id: 15,
      tags: "Just In",
      title: "Nike Pro Dri-FIT",
      description: "Men's Tight-Fit Sleeveless Top",
      color: "1 Colour",
      price: "MRP : ₹ 1 495.00",
      imagesUrls: "/AllProducts/pro15.png",
    },
    {
      id: 16,
      tags: "Just In",
      title: "Nike Dunk Low Retro",
      description: "Men's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 8 695.00",
      imagesUrls: "/AllProducts/pro16.png",
    },
    {
      id: 17,
      tags: "Just In",
      title: "Nike Air Max SC",
      description: "Women's Shoes",
      color: "2 Colours",
      price: "MRP : ₹ 5 995.00",
      imagesUrls: "/AllProducts/pro17.png",
    },
    {
      id: 18,
      tags: "Just In",
      title: "Nike Dri-FIT UV Miler",
      description: "Men's Short Sleeve Running Top",
      color: "1 Colour",
      price: "MRP : ₹ 1 695.00",
      imagesUrls: "/AllProducts/pro18.png",
    },
    {
      id: 19,
      tags: "Just In",
      title: "Nike Air Max SYSTM",
      description: "Older Kids' Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 6 495.00",
      imagesUrls: "/AllProducts/pro19.png",
    },
    {
      id: 20,
      tags: "Just In",
      title: "Nike Alate All U",
      description: "Women's Light Support Lightly Lined UNeck Printed Sports Bra",
      color: "1 Colour",
      price: "MRP : ₹ 2 195.00",
      imagesUrls: "/AllProducts/pro20.png",
    },
    {
      id: 21,
      tags: "Just In",
      title: "Nike Court Legacy Lift",
      description: "Women's Shoes",
      color: "2 Colours",
      price: "MRP : ₹ 7 495.00",
      imagesUrls: "/AllProducts/pro21.png",
    },
    {
      id: 22,
      tags: "Just In",
      title: "Nike Swoosh",
      description: "Women's Medium support Padded Sports Bra Tank",
      color: "2 Colours",
      price: "MRP : ₹ 3 095.00",
      imagesUrls: "/AllProducts/pro22.png",
    },
    {
      id: 23,
      tags: "Just In",
      title: "Nike SB Zoom Janoski OG+",
      description: "Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 8 595.00",
      imagesUrls: "/AllProducts/pro23.png",
    },
    {
      id: 24,
      tags: "Just In",
      title: "Nike Dri-FIT Run Division Rise 365",
      description: "Men's Running Tank",
      color: "2 Colours",
      price: "MRP : ₹ 3 495.00",
      imagesUrls: "/AllProducts/pro24.png",
    },
    {
      id: 25,
      tags: "Just In",
      title: "Nike Dri-FIT Challenger",
      description: "Men's 18cm (approx.) 2-in 1 Versatile Shorts",
      color: "1 Colour",
      price: "MRP : ₹ 2 495.00",
      imagesUrls: "/AllProducts/pro25.png",
    },
    {
      id: 26,
      tags: "Just In",
      title: "Jordan Series ES",
      description: "Men's Shoes",
      color: "2 Colours",
      price: "MRP : ₹ 7 495.00",
      imagesUrls: "/AllProducts/pro26.png",
    },
    {
      id: 27,
      tags: "Just In",
      title: "Nike Outdoor Play",
      description: "Older Kids' Oversized Woven Jacket",
      color: "1 Colour",
      price: "MRP : ₹ 3 895.00",
      imagesUrls: "/AllProducts/pro27.jpeg",
    },
    {
      id: 28,
      tags: "Just In",
      title: "Nike Sportswear Trend",
      description: "Older Kids' (Girls') High waisted Woven Shorts",
      color: "2 Colours",
      price: "MRP : ₹ 2 495.00",
      imagesUrls: "/AllProducts/pro28.png",
    },
    {
      id: 29,
      tags: "Just In",
      title: "Nike Blazer Low '77 Jumbo",
      description: "Women's Shoes",
      color: "1 Colour",
      price: "MRP : ₹ 8 595.00",
      imagesUrls: "/AllProducts/pro29.png",
    },
    {
      id: 30,
      tags: "Just In",
      title: "Nike SB Force 58",
      description: "Skate Shoe",
      color: "1 Colour",
      price: "MRP : ₹ 5 995.00",
      imagesUrls: "/AllProducts/pro30.png",
    },
   
  ];